import { Inter } from 'next/font/google'
import { getServerSession } from 'next-auth'
// import SessionProvider from '../sessProvider/sessionProvider'

//*COMPONENTS
import NavBar from './components/NavBar/NavBar'

//*STYLING
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  // const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <SessionProvider session={session}> */}
          <main>
            <NavBar/>
            {children}
          </main>
        {/* </SessionProvider> */}
      </body>
    </html>
  ) 
}
